"""add_entitlement_tables

Revision ID: 5dbecfa52786
Revises: create_component_folders
Create Date: 2026-01-28 23:49:07.593856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dbecfa52786'
down_revision: Union[str, Sequence[str], None] = 'create_component_folders'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('org_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('skill', 'tool', 'memory', name='registrycomponenttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'organization', 'public', name='componentvisibility'), nullable=False),
    sa.Column('component_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_stakeholders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'contributor', 'viewer', 'admin', name='stakeholderrole'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'user_id', name='uq_agent_stakeholder')
    )
    op.create_table('agent_user_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.Enum('viewer', 'user', 'contributor', 'admin', name='accesslevel'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'user_id', name='uq_agent_user_grant')
    )
    op.create_table('component_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['component_registry.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'agent_id', name='uq_component_agent_grant')
    )
    op.create_table('memory_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('suggested_name', sa.String(length=255), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=False),
    sa.Column('suggested_type', sa.String(length=20), nullable=True),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployment_id'], ['agent_deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # Removed auto-generated pgvector table drops - tables don't exist in this database
    # op.drop_index('mem0migrations_hnsw_idx', table_name='mem0migrations', ...)
    # op.drop_table('mem0migrations')
    # op.drop_index('semantic_memories_hnsw_idx', table_name='semantic_memories', ...)
    # op.drop_table('semantic_memories')
    op.drop_index('idx_agent_deployments_agent', table_name='agent_deployments')
    op.drop_index('idx_agent_deployments_status', table_name='agent_deployments')
    op.drop_index('idx_agent_deployments_version', table_name='agent_deployments')
    op.drop_index('idx_agent_library_refs_agent', table_name='agent_library_refs')
    op.drop_index('idx_agent_library_refs_component', table_name='agent_library_refs')
    op.add_column('agents', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('agents', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agents', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'agents', 'users', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'agents', 'agent_versions', ['current_version_id'], ['id'], use_alter=True)
    op.drop_index('ix_component_folders_version_id', table_name='component_folders')
    op.alter_column('component_library', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_component_library_author', table_name='component_library')
    op.drop_index('idx_component_library_type', table_name='component_library')
    op.drop_index('ix_components_folder_id', table_name='components')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_components_folder_id', 'components', ['folder_id'], unique=False)
    op.create_index('idx_component_library_type', 'component_library', ['type'], unique=False)
    op.create_index('idx_component_library_author', 'component_library', ['author_id'], unique=False)
    op.alter_column('component_library', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_component_folders_version_id', 'component_folders', ['version_id'], unique=False)
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'manager_id')
    op.drop_column('agents', 'organization_id')
    op.create_index('idx_agent_library_refs_component', 'agent_library_refs', ['library_component_id'], unique=False)
    op.create_index('idx_agent_library_refs_agent', 'agent_library_refs', ['agent_id'], unique=False)
    op.create_index('idx_agent_deployments_version', 'agent_deployments', ['version_id'], unique=False)
    op.create_index('idx_agent_deployments_status', 'agent_deployments', ['status'], unique=False)
    op.create_index('idx_agent_deployments_agent', 'agent_deployments', ['agent_id'], unique=False)
    # Removed auto-generated pgvector table recreations - tables didn't exist
    # op.create_table('semantic_memories', ...)
    # op.create_index('semantic_memories_hnsw_idx', ...)
    # op.create_table('mem0migrations', ...)
    # op.create_index('mem0migrations_hnsw_idx', ...)
    op.drop_table('memory_suggestions')
    op.drop_table('component_grants')
    op.drop_table('agent_user_grants')
    op.drop_table('agent_stakeholders')
    op.drop_table('component_registry')
    op.drop_table('organizations')
    # ### end Alembic commands ###
